# Generated by Django 4.0.6 on 2022-07-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodCals',
        ),
    ]
