# Generated by Django 4.0.6 on 2022-07-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0010_rename_user_foodlist_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(max_length=10)),
                ('food', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodApp.foodcals')),
            ],
        ),
    ]
