# Generated by Django 4.0.6 on 2022-07-14 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0011_portion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portion',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodApp.foodcals'),
        ),
    ]
