# Generated by Django 4.0.6 on 2022-07-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0012_alter_portion_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='portion',
            name='cals',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='food',
            field=models.ManyToManyField(to='FoodApp.portion'),
        ),
        migrations.AlterField(
            model_name='portion',
            name='weight',
            field=models.SmallIntegerField(),
        ),
    ]
