# Generated by Django 4.0.6 on 2022-07-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0013_portion_cals_alter_foodlist_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portion',
            name='meals',
            field=models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Snack')], default=1),
        ),
    ]
