# Generated by Django 4.0.6 on 2022-07-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0015_portion_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='days',
            field=models.SmallIntegerField(default=1),
        ),
    ]
