# Generated by Django 4.0.6 on 2022-07-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0016_foodlist_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='food',
            field=models.ManyToManyField(blank=True, null=True, to='FoodApp.portion'),
        ),
    ]
